Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/xenial64"

  config.vm.define "kube-dev" do |kube|
      kube.vm.hostname = "kube-dev"

      kube.vm.network "private_network", ip: "192.168.56.101"

      config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", 2048]
        vb.customize ["modifyvm", :id, "--cpus", 2]
      end

      config.vm.synced_folder "./app", "/home/vagrant/app", mount_options: ["dmode=775,fmode=777"]

      config.vm.provision "shell", path: "resources/java.sh"
      config.vm.provision "shell", path: "resources/bootstrap.sh"
  end

end