# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

   config.vm.box = "ubuntu/xenial64"

   config.vm.define "kube-01" do |kube|
      kube.vm.hostname = "kube-01"
      kube.vm.network "private_network", ip: "192.168.56.101"
      config.vm.provider :virtualbox do |vb|
         vb.customize ["modifyvm", :id, "--memory", 2048]
         vb.customize ["modifyvm", :id, "--cpus", 2]
      end  
      config.vm.provision "shell", inline: "export DEBIAN_FRONTEND=noninteractive"
      config.vm.provision "shell", path: "resources/bootstrap.sh"
   end

   config.vm.define "kube-02" do |kube|
      kube.vm.hostname = "kube-02"
      kube.vm.network "private_network", ip: "192.168.56.102"
      config.vm.provider :virtualbox do |vb|
         vb.customize ["modifyvm", :id, "--memory", 2048]
         vb.customize ["modifyvm", :id, "--cpus", 1]
      end
      config.vm.provision "shell", path: "resources/bootstrap.sh"
   end

   config.vm.define "kube-03" do |kube|
      kube.vm.hostname = "kube-03"
      kube.vm.network "private_network", ip: "192.168.56.103"
      config.vm.provider :virtualbox do |vb|
         vb.customize ["modifyvm", :id, "--memory", 2048]
         vb.customize ["modifyvm", :id, "--cpus", 1]
      end
      config.vm.provision "shell", path: "resources/bootstrap.sh"
   end

end