Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.define "ubuntu" do |ubuntu|

    config.vm.provider "virtualbox" do |vb|
        vb.name = "Ubuntu 16"
        vb.memory = "4096"
        vb.cpus = "4"
    end

    config.vm.network "private_network", ip: "192.168.33.10"

    config.vm.synced_folder ".", "/home/vagrant/docker", :mount_options => ["dmode=777", "fmode=666"]

  end

end