# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.box = "ubuntu/xenial64"

  config.vm.define :jenkins do |jenkins_config|
    jenkins_config.vm.hostname = 'jenkins'
    jenkins_config.vm.network "private_network", ip: "192.168.33.55"
  end

  config.vm.provider :virtualbox do |virtualbox_config|
      virtualbox_config.name = "Jenkins - Ubuntu 16.04"
      virtualbox_config.memory = "2024"
  end
  
  config.vm.provision "shell", path: "./bootstrap.sh"
end
